import com.centurylink.sdk.ApiGen;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ilya.drabenia' at '2/19/15 4:15 PM' with Gradle 2.2.1
 *
 * @author ilya.drabenia, @date 2/19/15 4:15 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ApiGen classUnderTest = new ApiGen();
    }
}
